name: .NET Core Build and Push

env:
  dotnet_version: '8.x' 

on:
  push:
    branches: [ 521-secrets.GITHUB_TOKEN ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet_version }}

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Pack with dotnet
      run: dotnet pack --configuration Release --output ./nupkg

    # 1.a-using PAT to push the package to github packages
    # - name: Push to GitHub Packages
    #   run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ env.packages_personal_access_token }} --source "https://nuget.pkg.github.com/priya-kinthali/index.json"
    #   env:
    #     packages_personal_access_token: ${{ secrets.PAT }}

    # 1.b-using new token without write permissions
    # - name: Push to GitHub Packages
    #   run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ env.packages_personal_access_token }} --source "https://nuget.pkg.github.com/priya-kinthali/index.json"
    #   env:
    #     packages_personal_access_token: ${{ secrets.PACKAGES_PERSONAL_ACCESS_TOKEN }}

    # 2.a-using github_token to push the package to github packages
    # - name: Push to GitHub Packages
    #   run: dotnet nuget push "./nupkg/*.nupkg" --source "https://nuget.pkg.github.com/priya-kinthali/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} 
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # 2.b-using github token 
    - name: Push to GitHub Packages
      run: dotnet nuget add source --username priya-kinthali --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/priya-kinthali/index.json"

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       










 
