name: .NET Core Build and Push

env:
  dotnet_version: '8.x' 

on:
  push:
    branches: [ 521-secrets.GITHUB_TOKEN ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet_version }}

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Push to GitHub Packages
      run: dotnet nuget push '**/*.nupkg' --api-key ${{ secrets.PAT }} --source https://nuget.pkg.github.com/priya-kinthali/index.json
      env:
        PAT: ${{ secrets.PAT }}









 
