name: Reproduce Setup-Dotnet 356

on:
  push:
    branches:
      - test-588
  workflow_dispatch:

jobs:
  setup-dotnet:
    strategy:
      matrix:
        os: [macos-26, macos-15-intel, macos-latest, macos-14]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Verify installation
        run: dotnet --version

      # - name: Show DOTNET_ROOT environment variable
      #   run: |
      #     echo "DOTNET_ROOT=$DOTNET_ROOT"
      - name: Set DOTNET_ROOT in GitHub Actions environment (macOS)
        run: |
          echo "DOTNET_ROOT=/custom/dotnet/path" >> $GITHUB_ENV
      - name: Show dotnet installation path
        run: which dotnet