name: Reproduce Setup-Dotnet 356

on: [push]

jobs:
  setup-dotnet:
    strategy:
      matrix:
        os: [windows-latest, macos-13, ubuntu-latest]
        # os: [ubuntu-latest]

      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        # uses: akv-platform/setup-dotnet@install-runtime-only
        with:
          dotnet-version: '9.0.x'

      - name: Verify installation
        run: dotnet --version