name: Reproduce Setup-Dotnet Failure-588issue

on: [push, pull_request]

jobs:
  setup-dotnet:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Verify installation
        run: dotnet --version