name: "setup-dotnet"
on: [push, pull_request]

description: "A wrapper around the official actions/setup-dotnet action with extra features"

inputs:
  dotnet-version:
    description: "Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x"
    required: false

  global-json-file:
    description: "Optional global.json location, if your global.json isn't located in the root of the repo."
    required: false

  strip-comments-from-global-json:
    description: "Whether to strip comments from the `global.json` file."
    default: true
    required: false

runs:
  using: "composite"

  steps:

    - shell: bash
      run: |
        case "${{ runner.os }}" in
          macOS) echo "DOTNET_INSTALL_DIR=/Users/runner/.dotnet" >> $GITHUB_ENV;;
          Linux) echo "DOTNET_INSTALL_DIR=/usr/share/dotnet" >> $GITHUB_ENV;;
          Windows) echo "DOTNET_INSTALL_DIR=C:\Program Files\dotnet" >> $GITHUB_ENV;;
          *) echo "::warning::Unsupported runner os: ${{ runner.os }}";;
        esac

    - shell: bash
      id: meta
      run: |
        if [[ -f "global.json" ]]; then
          echo "has-global-json=true" >> $GITHUB_OUTPUT
        else
          echo "has-global-json=false" >> $GITHUB_OUTPUT
        fi

    - shell: bash
      run: |
        if [[ "${{ steps.meta.outputs.has-global-json }}" == "true"  && "${{ inputs.strip-comments-from-global-json }}" == "true" ]]; then
          cp global.json global.json.copy
          npx -y strip-json-comments-cli global.json.copy > global.json
          rm global.json.copy
        fi

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        global-json-file: ${{ inputs.global-json-file }}
        source-url: ${{ inputs.source-url }}
        owner: ${{ inputs.owner }}
        config-file: ${{ inputs.config-file }}
        include-prerelease: ${{ inputs.include-prerelease }}
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.nuget_auth_token }}

    - shell: bash
      run: |
        if [[ "${{ steps.meta.outputs.has-global-json }}" == "true"  && "${{ inputs.strip-comments-from-global-json }}" == "true" ]]; then
          git checkout -- global.json
        fi

    - shell: bash
      run: dotnet --list-sdks