name: check wget
on:
  push:
    branches:
      - test-588
  workflow_dispatch:

jobs:
  Architecture:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [macos-latest, ubuntu-latest, windows-latest, ubuntu-24.04-arm, windows-11-arm]
            arch: [x64, x86, arm64, amd64, arm, s390x, ppc64le, riscv64]
            

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # - uses: actions/setup-dotnet@v5
      #   with:
      #    dotnet-version: | 
      #             8.0.x
      #             8.0.x
      # - run: dotnet --info

      # - uses: lmvysakh/setup-dotnet@support_architecture
      - uses:  lmvysakh/setup-dotnet@support_architecture_new
        with:
         Architecture : ${{ matrix.arch }}
         dotnet-version: | 
                  10.0.102
              
      - run: dotnet --info