name: check cross arch
on:
  push:
    branches:
      - test-588
  workflow_dispatch:

jobs:

  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [macos-latest, ubuntu-latest, windows-latest, ubuntu-24.04-arm, windows-11-arm]        

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
          dotnet --info
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          cache: true
          cache-dependency-path: Library/packages.lock.json
        #  dotnet-quality: 'preview'
        # global-json-file: csharp/global.json
        #  dotnet-version: | 
        #           9.0.308
        #           10.0.101     
      - run: dotnet --info
      - run: dotnet restore --locked-mode
  
  crossarchitecture:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [macos-latest, ubuntu-latest, windows-latest, ubuntu-24.04-arm, windows-11-arm]
            arch: [x64, x86, arm64]           

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
          dotnet --info
      - uses:  priya-kinthali/setup-dotnet@test-524
        with:
         architecture : ${{ matrix.arch }}
         dotnet-version: '10.0.x'
         cache: true
         cache-dependency-path: Library/packages.lock.json
        #  dotnet-quality: 'preview'
        #  global-json-file: csharp/global.json
        #  dotnet-version: | 
        #           9.0.308
        #           10.0.101     
      - run: dotnet --info
      - run: dotnet restore --locked-mode