name: check dotnet latest
on:
  push:
    branches:
      - test-588
  workflow_dispatch:

jobs:
  Architecture:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [macos-latest, ubuntu-latest, windows-latest, windows-11-arm, macos-15-intel, ubuntu-24.04-arm]
            # os: [ubuntu-latest, windows-latest, macos-latest]
            # arch: [x64, x86, arm64]   

            
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # - name: Clear dotnet cache
      #   if: runner.os != 'Windows'
      #   run: rm -rf $HOME/.dotnet
      # - name: Clear dotnet cache (Windows)
      #   if: runner.os == 'Windows'
      #   run: Remove-Item -Recurse -Force $env:USERPROFILE\.dotnet
      #   shell: pwsh
      
      # - name: Set DOTNET_INSTALL_DIR
      #   if: runner.os == 'Linux' || runner.os == 'macOS'
      #   run: echo "DOTNET_INSTALL_DIR=${{ runner.temp }}/.dotnet" >> $GITHUB_ENV
      # - name: Set DOTNET_INSTALL_DIR
      #   if: runner.os == 'Windows'
      #   shell: pwsh
      #   run: |
      #     "DOTNET_INSTALL_DIR=$env:USERPROFILE\.dotnet" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append 
      - uses: mahabaleshwars/setup-dotnet@feature/497-dotnet-version-latest-keyword
      # - uses: actions/setup-dotnet@v5
        id: stepid
        with:
          # dotnet-version: '8.0'
          # global-json-file: 'csharp/global.json'
          dotnet-version: latest           
          # cache: true
          # cache-dependency-path: src/Library/packages.lock.json
          dotnet-channel: 'lts'
          # architecture : ${{ matrix.arch }}
          dotnet-quality: 'preview'

      # - name: Echo DOTNET_INSTALL_DIR and DOTNET_ROOT (Linux/macOS)
      #   if: runner.os == 'Linux' || runner.os == 'macOS'
      #   run: |
      #     echo "DOTNET_INSTALL_DIR=$DOTNET_INSTALL_DIR"
      #     echo "DOTNET_ROOT=$DOTNET_ROOT"

      # - name: Echo DOTNET_INSTALL_DIR and DOTNET_ROOT (Windows)
      #   if: runner.os == 'Windows'
      #   shell: pwsh
      #   run: |
      #     Write-Host "DOTNET_INSTALL_DIR=$env:DOTNET_INSTALL_DIR"
      #     Write-Host "DOTNET_ROOT=$env:DOTNET_ROOT"
      - run: dotnet --info
      - run: echo '${{ steps.stepid.outputs.dotnet-version }}' # outputs 8.0.416
      # - run: dotnet restore --locked-mode
  

