name: check channel
on:
  push:
    branches:
      - test-588
  workflow_dispatch:

jobs:
  setupDotnet_main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, windows-11-arm, macos-15-intel, ubuntu-24.04-arm]
        dotnet-version: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
        # arch: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

  setupDotnet_pr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, windows-11-arm, macos-15-intel, ubuntu-24.04-arm]
        dotnet-version: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: akoeplinger/setup-dotnet@fix-releases
        with:
          dotnet-version: ${{ matrix.dotnet-version }}