name: Reproduce Setup-Dotnet 674

on:
  push:
    branches:
      - test-588
  workflow_dispatch:

jobs:
  setup-dotnet:
    strategy:
      matrix:
        os: [macos-latest, macos-14-large]

      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
    

      - name: Verify installation
        run: dotnet --version

      - name: List installed SDKs
        run: dotnet --list-sdks

      - name: List installed runtimes
        run: dotnet --list-runtimes